In [1]:
%pip install pandas
%pip install scikit-learn
%pip install numpy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
from sklearn.linear_model import Perceptron

In [3]:
dataset_or = pd.read_csv('OR.csv')
data_or = dataset_or.iloc[:,:-1]
label_or = dataset_or.iloc[:,-1]

clf = Perceptron(tol=1e-3, random_state=0)
clf.fit(data_or, label_or)
print(clf.score(data_or,label_or))
print(clf.predict(data_or))

1.0
[0 1 1 1]


In [4]:
dataset_and = pd.read_csv('AND.csv')
data_and = dataset_and.iloc[:,:-1]
label_and = dataset_and.iloc[:,-1]

clf = Perceptron(tol=1e-3, random_state=0)
clf.fit(data_and, label_and)
print(clf.score(data_and,label_and))
print(clf.predict(data_and))

1.0
[0 0 0 1]


In [5]:
dataset_xor = pd.read_csv('XOR.csv')
data_xor = dataset_xor.iloc[:,:-1]
label_xor = dataset_xor.iloc[:,-1]

clf = Perceptron(tol=1e-3, random_state=0)
clf.fit(data_xor, label_xor)
print(clf.score(data_xor,label_xor))
print(clf.predict(data_xor))

0.5
[0 0 0 0]


In [6]:
import pandas as pd
from sklearn.neural_network import MLPClassifier as MLP

In [7]:
dataset_mlp_xor = pd.read_csv('XOR.csv')
data_mlp_xor = dataset_mlp_xor.iloc[:,0:-1]
label_mlp_xor = dataset_mlp_xor.iloc[:,-1]

model = MLP(hidden_layer_sizes=(4), max_iter=10000, activation = 'relu', random_state=99)
model.fit(data_mlp_xor,label_mlp_xor)

print('score:', model.score(data_mlp_xor,label_mlp_xor))
print('predictions:', model.predict(data_mlp_xor))

score: 1.0
predictions: [0 1 1 0]


In [8]:
from sklearn.model_selection import train_test_split

dataset_heart = pd.read_csv('heart.csv')
data_heart = dataset_heart.iloc[:, :-1]
label_heart = dataset_heart.iloc[:, -1]

xtrain, xtest, ytrain, ytest = train_test_split(data_heart, label_heart, test_size=0.3, random_state=5)

In [11]:
model_heart = MLP(hidden_layer_sizes=(10), max_iter=1000, activation = 'relu', solver='lbfgs', random_state=1000)
model_heart.fit(xtrain, ytrain.values.ravel())

print('score train:', model_heart.score(xtrain,ytrain))

score train: 0.839622641509434


In [12]:
print('score test:', model_heart.score(xtest,ytest))

score test: 0.8571428571428571
