In [63]:
%pip install numpy
%pip install pandas
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [64]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [65]:
dataset = pd.read_csv('milk.csv')
train_data = np.array(dataset)[:, 0:-1]
train_label = np.array(dataset)[:, -1]

train_data

array([[6.6, 35, 1, ..., 1, 0, 254],
       [6.6, 36, 0, ..., 0, 1, 253],
       [8.5, 70, 1, ..., 1, 1, 246],
       ...,
       [3.0, 40, 1, ..., 1, 1, 255],
       [6.8, 43, 1, ..., 1, 0, 250],
       [8.6, 55, 0, ..., 1, 1, 255]], dtype=object)

In [72]:
train_label

array(['high', 'high', 'low', ..., 'low', 'high', 'low'], dtype=object)

In [66]:
sc = MinMaxScaler(feature_range=(0,1))
train_data = sc.fit_transform(train_data)

In [73]:
train_data

array([[0.55384615, 0.01785714, 1.        , ..., 1.        , 0.        ,
        0.93333333],
       [0.55384615, 0.03571429, 0.        , ..., 0.        , 1.        ,
        0.86666667],
       [0.84615385, 0.64285714, 1.        , ..., 1.        , 1.        ,
        0.4       ],
       ...,
       [0.        , 0.10714286, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.58461538, 0.16071429, 1.        , ..., 1.        , 0.        ,
        0.66666667],
       [0.86153846, 0.375     , 0.        , ..., 1.        , 1.        ,
        1.        ]])

In [74]:
KNN = KNeighborsClassifier(n_neighbors=3, weights='distance')
KNN.fit(train_data, train_label)

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [70]:
ph = float(input('Masukkan input ph:'))
temp = int(input('Masukkan input temp:'))
taste = int(input('Masukkan input taste:'))
odor = int(input('Masukkan input odor:'))
fat = int(input('Masukkan input fat:'))
turbidity = int(input('Masukkan input turbidity:'))
colour = int(input('Masukkan input colour:'))

test_data = np.array([ph, temp, taste, odor, fat, turbidity, colour])
test_data = sc.transform(np.reshape(test_data, (1, -1)))

test_data

array([[0.55384615, 0.05357143, 0.        , 0.        , 0.        ,
        0.        , 1.        ]])

In [71]:
hasil = KNN.predict(test_data)
hasil

array(['medium'], dtype=object)

In [75]:
dataset_training = pd.read_csv('milk_training.csv')
training_train_data = np.array(dataset_training)[:, 0:-1]
training_train_label = np.array(dataset_training)[:, -1]

In [76]:
training_train_data

array([[6.6, 35, 1, ..., 1, 0, 254],
       [6.6, 36, 0, ..., 0, 1, 253],
       [6.6, 37, 1, ..., 1, 1, 255],
       ...,
       [6.7, 41, 1, ..., 0, 0, 247],
       [6.8, 41, 0, ..., 0, 0, 255],
       [6.8, 38, 0, ..., 0, 0, 255]], dtype=object)

In [77]:
training_train_label

array(['high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
      

In [ ]:
training_train_data = sc.fit_transform(training_train_data)
training_train_data

array([[0.55384615, 0.01785714, 1.        , ..., 1.        , 0.        ,
        0.93333333],
       [0.55384615, 0.03571429, 0.        , ..., 0.        , 1.        ,
        0.86666667],
       [0.55384615, 0.05357143, 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.56923077, 0.125     , 1.        , ..., 0.        , 0.        ,
        0.46666667],
       [0.58461538, 0.125     , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.58461538, 0.07142857, 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [78]:
dataset_testing = pd.read_csv('milk_testing.csv')
testing_test_data = np.array(dataset_testing)[:, :-1]
testing_test_label = np.array(dataset_testing)[:, -1]


In [79]:
testing_test_data

array([[6.8, 45, 1, ..., 1, 0, 245],
       [6.6, 37, 1, ..., 1, 1, 255],
       [6.7, 38, 1, ..., 1, 0, 255],
       ...,
       [6.5, 37, 0, ..., 0, 0, 255],
       [6.5, 40, 1, ..., 0, 0, 250],
       [6.7, 45, 1, ..., 0, 0, 247]], dtype=object)

In [80]:
testing_test_label

array(['high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'high', 'high', 'high',
       'high', 'high', 'high', 'high', 'high', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
       'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low', 'low',
      

In [ ]:
testing_test_data = sc.transform(testing_test_data)
testing_test_data

array([[0.58461538, 0.19642857, 1.        , ..., 1.        , 0.        ,
        0.33333333],
       [0.55384615, 0.05357143, 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.56923077, 0.07142857, 1.        , ..., 1.        , 0.        ,
        1.        ],
       ...,
       [0.53846154, 0.05357143, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.53846154, 0.10714286, 1.        , ..., 0.        , 0.        ,
        0.66666667],
       [0.56923077, 0.19642857, 1.        , ..., 0.        , 0.        ,
        0.46666667]])

In [ ]:
KNN.fit(training_train_data, training_train_label)

predictions = KNN.predict(testing_test_data)
accuracy = accuracy_score(testing_test_label, predictions)
print("Accuracy:", accuracy)

Accuracy: 0.9936908517350158
